server:
  port: 8761

spring:
  application:
    name: eureka-server


eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: false
    fetch-registry: false